[Inhaltsverzeichnis](table_of_contents.ipynb)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# 4 Datenkomprimierung durch Dimensionsreduktion
## 4.1 Merkmalsselektion
## 4.2 Merkmalbearbeitung - Hauptachsentransformation
Vorgehen:
- Mittelwertvektors
- Kovarianzmatrix
- Eigenwerte und Eigenvektoren der Kovarianzmatrix

Eigenwertproblem:

$
\textbf{S} \cdot \vec{x} = \lambda \cdot \vec{x}
$

mit:
- $\vec{x} \ldots $ Eigenvektoren
- $\lambda \ldots $ Eigenwerte

$
\left(\textbf{S} - \lambda \textbf{E}\right) \vec{x} = 0
$

$
det\left(\textbf{S} - \lambda \textbf{E}\right) = 0
$

- Normierung der Eigenvektoren
- Transformationsmatrix (Eigenvektoren bilden die Spalten)

[Beispiel 1 + 2](example_pca.ipynb)

[Beispiel 3](pca_soccer.ipynb)

## 4.3 Merkmalgenerierung als Zufallsprozess
### 4.3.1 Mittelwert
Beispiel

Die Datenmatrix enthält pro Zeile eine Realisierung und pro Spalte ein Merkmal.

In [32]:
sp = np.array([1,2,3,2,7,2,1,8,5]).reshape(3,3)    
print('Datenmatrix:\n',sp)
mean_vec = np.mean(sp, axis=0)
print('Mittelwertvektor:\n',mean_vec.T)

Datenmatrix:
 [[1 2 3]
 [2 7 2]
 [1 8 5]]
Mittelwertvektor:
 [ 1.33333333  5.66666667  3.33333333]


### 4.3.2 Varianz
### 4.3.3 Kovarianz
Beispiel

In [31]:
cov_mat = np.cov(sp, ddof=0)
print('Kovarianzmatrix:\n',cov_mat)

Kovarianzmatrix:
 [[ 0.66666667  0.          1.33333333]
 [ 0.          5.55555556  5.55555556]
 [ 1.33333333  5.55555556  8.22222222]]
